### ISSUE TITLE
Publishing to maven central

### ISSUE THREAD

**Issue by lbergelson** [lindenb/jbwa#10]
Since we're using jbwa as a dependency for [gatk4](github.com/broadinstitute/gatk), we'd like to make jbwa available through maven central at some point in the not to distant future.  We currently published a version on our [own artifactory repository](https://artifactory.broadinstitute.org/) to enable us to use it during development, but we can't rely on that when we make releases to maven central.  

Would you be willing to publish it to central?  We could offer help but there would be some work you'd have to do to get accounts set up.

Alternatively, we could publish it ourselves under whatever name you prefer (com.github.lindenb:jbwa being one possible option), or we could fork the repo and publish our fork under our own name.  (org.broadinstitute:jbwa) 

Would any of these options work for you?

**Comment by lindenb** [comment]
> Would you be willing to publish it to central?

@lbergelson yes, I don't have any problem with that.

Your favorite choice will be mine (as long as I'm credited somewhere :-) [ ego.. ego.. ] ). Things will go faster for the gatk team if you  manage the whole transition to maven. 

Just in case, I'll add you as a collaborator in jbwa if it can help.

P

**Comment by lbergelson** [comment]
Thanks for the response.  I think the best thing to do would be for me to set it up so that it can be published under you're name.  We definitely want you credited!  What package name do you prefer?  com.github.lindeb would be one option, but if you have a personal domain you'd rather use we can do that instead.

**Comment by lindenb** [comment]
> com.github.lindeb would be one option

"com.github.lindenb" is ok :-)     lindenb not lindeb please :-)

**Comment by lbergelson** [comment]
Ack!   Sorry about that typo.  I'll be sure to get it right on maven :)

**Comment by lbergelson** [comment]
I've created an issue on the OSS sonatype jira for them to create a new project for publishing jbwa.  Feel free to create an account and comment on the ticket so you can be given ownership of the project. ( https://issues.sonatype.org/browse/OSSRH-23336. )  Once they approve it then we can upload artifacts.

**Comment by lbergelson** [comment]
Closing because this is completed.
